/*
	空间线相关事件
*/

FDPAction_SpaceLine_Create = function( viewer, id, time, color, array, width, linewidth, linecolor,bshow )
{
}

FDPAction_SpaceLine_Visible = function( viewer,id, time, bShow )
{
}

FDPAction_SpaceLine_闪烁 = 
{
}

/*

	array    时间，百分比，构成的一个数组。  time0, Scale0, time1, scale1........
*/
FDPAction_SpaceLine_生长 = function( viewer, id, array )
{
	
}

FDPAction_SpaceLine_color = function( viewer, id, time, color, linecolor )
{
}

//FDPAction_SpaceLine_width = function( 